	
	-- 17025 Tickets en total
	SELECT DISTINCT TICKET_NUMERO, CAJA_NUMERO, CAJA_TIPO, SUCURSAL_NOMBRE, EMPLEADO_DNI FROM gd_esquema.Maestra
	where CAJA_NUMERO is not null
		

	-- 6862 Tickets con cliente y pago con tarjeta	
	SELECT DISTINCT TICKET_NUMERO, CLIENTE_DNI ,PAGO_TARJETA_NRO,PAGO_TIPO_MEDIO_PAGO, PAGO_MEDIO_PAGO FROM gd_esquema.Maestra 
	WHERE CLIENTE_DNI IS NOT NULL
	ORDER BY CLIENTE_DNI, TICKET_NUMERO

	-- 2513 Tickets en efectivo => No tienen clientes
	SELECT DISTINCT TICKET_NUMERO, CLIENTE_DNI ,PAGO_TARJETA_NRO,PAGO_TIPO_MEDIO_PAGO, PAGO_MEDIO_PAGO FROM gd_esquema.Maestra 
	WHERE PAGO_MEDIO_PAGO = 'Efectivo'
	ORDER BY CLIENTE_DNI, TICKET_NUMERO

	SELECT DISTINCT TICKET_NUMERO, CLIENTE_DNI, SUCURSAL_NOMBRE, CAJA_NUMERO, CAJA_TIPO,PAGO_MEDIO_PAGO, ENVIO_COSTO FROM gd_esquema.Maestra 
	ORDER BY TICKET_NUMERO

	SELECT DISTINCT SUCURSAL_NOMBRE, TICKET_NUMERO, EMPLEADO_DNI, CAJA_NUMERO, CAJA_TIPO, PAGO_MEDIO_PAGO, CLIENTE_DNI, CLIENTE_DOMICILIO, ENVIO_COSTO FROM gd_esquema.Maestra
	ORDER BY TICKET_NUMERO

	-- PAGO TARJETA NUMERO ES UN NUMERO DE TARJETA O EL NUMERO DE PAGO CON TARJETA???

	SELECT * FROM gd_esquema.Maestra 
	
	ORDER BY TICKET_NUMERO
	
	SELECT DISTINCT PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION FROM gd_esquema.Maestra
	WHERE PRODUCTO_DESCRIPCION IS NOT NULL
	ORDER BY PRODUCTO_NOMBRE 


	SELECT DISTINCT TICKET_NUMERO, TICKET_TIPO_COMPROBANTE FROM gd_esquema.Maestra
	ORDER BY TICKET_NUMERO



	SELECT DISTINCT TICKET_NUMERO,CLIENTE_DNI, PAGO_MEDIO_PAGO, PAGO_TIPO_MEDIO_PAGO, TICKET_TOTAL_ENVIO, ENVIO_HORA_FIN, PAGO_TARJETA_NRO  FROM gd_esquema.Maestra
	ORDER BY TICKET_NUMERO
	-- TICKET QUE NO TIENE NADA DEL CLIENTE :)
	SELECT * FROM gd_esquema.Maestra WHERE TICKET_NUMERO = 1351318314
